### ISSUE TITLE
local sharing

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#1004]
**User story**

As a _user downloading content_ I want _local sharing_ so that _bandwidth usage is reduced_.

(If work duration will exceed five days, must be broken down into multiple)

**Tasks** 

- [x] (Designer) Complete [wireframe](https://balsamiq.cloud/sagy57t/podvg7r) designs for all screens to be added or modified
- [x] (Developer) Create new branch and pull request.
- [x] (Tester) Create Jenkins job to build automatically on commit and nightly end-to-end build of branch
- [ ] (Tester) Update end-to-end testing scenarios in accordance with user story
- [ ] (Tester) Add Cypress and Maestro tests to branch based on testing scenarios/wireframes
- [x] (Developer) Implement code as per design and acceptance criteria: requires successful Jenkins build and end-to-end build. Post video of completion of acceptance criteria on task card. Self check for at least 5-10 minutes.
  - [ ] Development subtasks can go here
- [ ] (Tester) check/verify - run any manual sanity checks required

**Acceptance criteria**

A new branch should be created and [end-to-end testing scenarios](https://github.com/UstadMobile/UstadMobile/tree/primary/test-end-to-end) should be added or modified as required for the user story. Then add links below for all testing scenarios that are newly added or significantly modified:

* [scenario link1](link-to-markdown-for-scenario-in-branch.md) 
* [scenario link2](link-to-markdown-for-scenario-in-branch.md)
