### ISSUE TITLE
Simplified onboarding inc passkey support and invitation support

### ISSUE THREAD

**Issue by divyahariharan2103** [UstadMobile/UstadMobile#906]
[<img src="https://devserver3.ustadmobile.com/jenkins/job/dev-simplified-onboarding/badge/icon?subject=Build">](https://devserver3.ustadmobile.com/jenkins/job/dev-simplified-onboarding/)

[<img a src="https://devserver3.ustadmobile.com/jenkins/job/dev-simplified-onboarding-End-To-End-Tests/badge/icon?subject=End-To-End-Tests">](https://devserver3.ustadmobile.com/jenkins/job/dev-simplified-onboarding-End-To-End-Tests/)

[<img a src="https://devserver3.ustadmobile.com/jenkins/job/dev-simplified-onboarding-invite-user-e2e-End-To-End-Tests/badge/icon?subject=Invite-User-E2E-Test">](https://devserver3.ustadmobile.com/jenkins/job/dev-simplified-onboarding-invite-user-e2e-End-To-End-Tests/)

As a (parent) I want (to login without creating a new username/password) so that (signup is easier and I don't have to remember usernames, passwords, phone numbers, etc.

Background info on user story:

* Critical: as a parent you need to be able to add multiple accounts for children (e.g. for multiple children who share the same phone)
* (Maybe later) As a parent you need to be able to add permission for another parent (e.g. account for child first added on mom's phone, now they want to use their dad's phone)

New user scenarios:

In all cases user might or might not have an existing account.

* Individual
  * Might be a parent, adult learner/teenager, or teacher
  * Might be using an existing content library set (eg. Learning Tree existing content) or blank (e.g. existing individual learner mode) - _edge case question: what if they want to use more than one content collection?_
* Existing school/organization
  * Might be a parent, learner with own account (e.g. teenage student, university student, adult learner, etc), or teacher
  * Might be a young child (with badge)
  * Likely needs a searchable list of sites/communities/schools (need to find the right word here - synonymous to 'workspace' on Slack).
  * User might have existing account, system might (or might not) allow registration of new users, might (or might not) allow registration of those with an invite link
* New school/organization

**Design tasks:**
- [x] @mikedawson  to create a list of all registration scenarios for Akshat (8/Jul)
- [x] @akshattak to create flow diagram (9/Jul) [on Miro Board](https://miro.com/app/board/uXjVK_znzJg=/)
- [x] @akshattak to create screen designs after flow is checked

**Implementation tasks:**

- [x] Terms and Conditions page to be added as part of Sign up
- [x] @Nikunjsharma0  Adding learning space list screen
- [x] @Nikunjsharma0 web version of screens and same flow (16/Sep)
- [x] @Nikunjsharma0 implement add learning space command, add centraldb to client app, show list of known learning spaces in learning space list (23/Sep).
- [x] @Nikunjsharma0 test / handle all url config parameters - including systems that have a single preset learning space url.
**NewOrExistingAccount screen**: (30/9)

* If preset url is not null
    * if registration not allowed on preset url: navigate directly to the login screen for preset learning space url. When navigating, pop this screen off the back stack. Going back should not return to this screen when navigation happened automatically. Do not use clear stack because this will cause a problem when the flow is used from account list screen. 
    * If registration is allowed - allow user to select new or existing account. When the user clicks on of these options, they should go directly to signup or login for the given learning space
* If personal learning space is null
    * When the user taps new or existing account, then go directly to learning space list screen  
* If personal learning space is not null
    * Go to PersonalOrLearningSpace screen

- [x] @Nikunjsharma0 handle when learning space does not allow new user registration
- [x] @Nikunjsharma0 AccountList add another account button should trigger the same flow as starting the app for the first time (19/Sept)
- [x] @poojaustad update Maestro end-to-end testing so all applicable existing tests pass (19/Sept)
- [x] @poojaustad update cypress end-to-end testing so all applicable existing tests pass (24/Sept).
- [x] @mikedawson setup end to end testing environment to use https
- [x] @mikedawson to fix web version to workaround Door database/JS bug (Door does not support multiple databases on Javascript)
- [x] @poojaustad to update test descriptions to reflect changes
- [x] @Nikunjsharma0 to update credential manager API usage - set ```preferImmediatelyAvailableCredentials``` to true so that the dialog will not appear if there are no saved credentials. Add support for saving normal passwords using password manager.
- [x] @Nikunjsharma0 invitations should expire after 7 days (add field for expiration - that is time of issue plus 7 days converted into milliseconds) .
- [x] @Nikunjsharma0 create http endpoint, that can be enabled using KTOR configuration setting so that automated tests can access email 'sent'. If ktor config setting ```useMockEmail``` is set to true, then bind a dummy implementation of the email sender and provide an http endpoint that can list all emails sent to a specific address e..g. /api/testemail/list?to=user@email.com - provides json list of subject/text.
- [x] @Nikunjsharma0 update sign-up screen to ensure that if the user is signing up using an invite link that they should be redeemed, and they should be enrolled (without having to go to another screen - e.g. directly in the signup screen). This can be checked by looking for the 'NEXT' argument. Once signup is completed - they should go to the list of courses, and they should see the course in which they are enrolled (e.g. as student or teacher). - Expected 7/Feb
- [x] @Nikunjsharma0 update sign-up view model to handle NEXT argument similarly to Login view model Expected 7/Feb .
- [x] @mikedawson merge primary (including reduced end to end execution time changes) update testserver controller to create learning space etc as required for end-to-end tests to run (12/Feb)
- [x] @poojaustad update tests merging primary (including reduced end to end execution time changes) update for all existing end-to-end tests to pass (14/Feb)
- [x] @Nikunjsharma0 to update handling of passkey rpId such that (17/Feb - 14/Feb if possible)
  - [x] rpId (passkeyRpId as per SystemUrlConfig) will be the hostname (without protocol, port, or path as per passkey specs) of systemBaseUrl. App will use one rpId for all passkeys generated. Passkey id will be
    - [x] ```username@schoolname.example.org``` when using https on default port 
    - [x] ```username@schoolname.example.org:1234``` when using https on non-default port 
    - [x] ```username@http://schoolname.example.org[:port]``` when using non-https 
  - [x] When the user creates a passkey, uninstalls (e.g. using a new device or reset device etc), then the first screen (neworexistingaccount) should show credential manager using prefer available credentials = true (e.g. the sheet will show only if an account is available). This will include both passkeys and saved username/passwords. If the user selects an account the app must login to the selected learning space.

**Acceptance criteria**

~~7.1 [Admin can enable/disable registration for users](https://github.com/UstadMobile/UstadMobile/blob/dev-simplified-onboarding/test-end-to-end/test-descriptions/007_001_admin_enable_or_disable_user_registration_test_description.md)~~

7.2a ~~[When registration is enabled: Users over 13 can register directly on learning space by creating a passkey](https://github.com/UstadMobile/UstadMobile/blob/dev-simplified-onboarding/test-end-to-end/test-descriptions/007_002a_user_registration_above_age_13_test_description.md)~~

7.2b ~~[When registration is enabled: Users over 13 can register directly on learning space by creating a username and password](https://github.com/UstadMobile/UstadMobile/blob/dev-simplified-onboarding/test-end-to-end/test-descriptions/007_002b_user_registration_above_age_13_test_description.md)~~

7.2c ~~[When personal accounts are enabled by setting a personal learning space URL: users over 13 can register a personal account directly by creating a passkey](https://github.com/UstadMobile/UstadMobile/blob/dev-simplified-onboarding/test-end-to-end/test-descriptions/007_002c_user_registration_above_age_13_test_description.md)~~

7.2d ~~[When personal accounts are enabled by setting a personal learning space URL: users over 13 can register a personal account directly by creating a username and password](https://github.com/UstadMobile/UstadMobile/blob/dev-simplified-onboarding/test-end-to-end/test-descriptions/007_002c_user_registration_above_age_13_test_description.md)~~

7.2e ~~[When personal accounts are enabled by setting a personal learning space URL: parents can register and add child profiles](https://github.com/UstadMobile/UstadMobile/blob/dev-simplified-onboarding/test-end-to-end/test-descriptions/007_002e_user_registration_personalal_account_can_add_child_profiles.md)~~

**Comment by mikedawson** [comment]
Theme designs:

Splash:
![splash](https://github.com/user-attachments/assets/a5c31fb5-00b6-4e2f-b4a0-d07010df161c)

Signup:
![signup](https://github.com/user-attachments/assets/5be6fc8e-3e2d-4dad-aec7-3f77fa6e1a64)

Library:
![library](https://github.com/user-attachments/assets/5ba87916-e5bf-400a-9a8d-e1d58f5d4c8c)

**Comment by divyahariharan2103** [comment]
To be wrapped up with the sever side verification by this Wednesday (August 7th)

**Comment by divyahariharan2103** [comment]
Passkeys during Sign up and Sign In process:



![Image](https://github.com/user-attachments/assets/d742d62f-d8b9-4e2d-b103-bb4f83f5eabd)





![Image](https://github.com/user-attachments/assets/0cebae3b-beaa-48ae-81b6-4c056de784ef)





![Image](https://github.com/user-attachments/assets/6ec35f15-5f2d-42fb-86a6-7813258fb2e2)

**Comment by Nikunjsharma0** [comment]
![Image](https://github.com/user-attachments/assets/2104098a-36dc-40ff-9667-d7dbe2d2a10e)



![Image](https://github.com/user-attachments/assets/f5e70314-f10e-4fe3-8918-7409d228c6a5)

![Image](https://github.com/user-attachments/assets/9a88d352-b5df-4514-a6cc-d44531526d2c)



![Image](https://github.com/user-attachments/assets/faa9360b-caca-4efe-96bb-925ff922c6a2)




![Image](https://github.com/user-attachments/assets/a6d82854-f360-481d-91b1-bf08ea241b16)

**Comment by mikedawson** [comment]
Handling local accounts behavior:
Create a new local account: new user, personal, other options, create local account
In future (not in current version): Restore from backup: existing user, personal, (goes to login screen) ; login screen shows a button Restore local account backup. Currently restore local account is not available.

We should not use the 'individual' user term - use personal - because personal accounts often have child profiles (e.g. it is not a single individual).

**Comment by Nikunjsharma0** [comment]
New user can create personal account using passkey on Android:


https://github.com/user-attachments/assets/abb90b74-5cc5-43f1-bc25-b1280bf09a9f

**Comment by Nikunjsharma0** [comment]
Connecting with an existing username and password to an existing learning space works as before



https://github.com/user-attachments/assets/caa0599c-0dc5-4b34-a908-0231dd557664

**Comment by mikedawson** [comment]
Behavior note: on the signup screen - if a user has not completed all mandatory fields; then clicking signup or other options will not navigate - will highlight mandatory fields instead.

**Comment by mikedawson** [comment]
Behavior note: creating a new account on device without passkey support
If user will have an option to create a local account (local account must be supported by platform - Android/Desktop and must be a personal account): Signup button should be "Next", then go to the more options screen, and allow the user to choose between creating a username and password or creating a local only account
If user does not have the option to create a local account; then username and password are included in the fields on signup screen and are mandatory. Button text will be Signup.

**Comment by Nikunjsharma0** [comment]
New user can create personal account using username/password on all supported platforms


https://github.com/user-attachments/assets/9a152c11-236c-412a-a745-fcede8862168

**Comment by Nikunjsharma0** [comment]
Existing personal account user can sign-in using passkey on Android:



https://github.com/user-attachments/assets/a124b864-e82f-4d82-90ad-d6409b88d4a4

**Comment by mikedawson** [comment]
> New user can create personal account using username/password on all supported platforms
> XRecorder_Edited_11092024_185055.mp4

(not critical - but should be updated) We should not have the checkboxes for parent/teacher and profile photo where the user provides their username and password. these were already in the signup screen.

**Comment by Nikunjsharma0** [comment]
Existing personal account user with username and password can sign-in on all existing platforms


https://github.com/user-attachments/assets/8fc5de0a-7eac-4c77-8de2-8b59edfb3965

**Comment by poojaustad** [comment]
The acceptance criteria have been tested and are working as expected.

**Comment by mikedawson** [comment]
Issues #951 #952 and #953 need resolved before this can be distributed (even as a preview)

**Comment by Nikunjsharma0** [comment]
https://github.com/UstadMobile/UstadMobile/issues/950

https://github.com/UstadMobile/UstadMobile/issues/951

https://github.com/UstadMobile/UstadMobile/issues/952

https://github.com/UstadMobile/UstadMobile/issues/953

Video for all 4 issues @poojaustad 

https://github.com/user-attachments/assets/324c08d5-7af5-41fb-9f2f-e6e4a4e7dd78

**Comment by Nikunjsharma0** [comment]
https://github.com/UstadMobile/UstadMobile/blob/dev-simplified-onboarding/test-end-to-end%2Ftest-descriptions%2F007_001_admin_enable_or_disable_user_registration_test_description.md


https://github.com/user-attachments/assets/bb818af1-adbe-48de-8b8b-10cd8527ea27

**Comment by Nikunjsharma0** [comment]
https://github.com/UstadMobile/UstadMobile/blob/dev-simplified-onboarding/test-end-to-end%2Ftest-descriptions%2F007_002a_user_registration_above_age_13_test_description.md


https://github.com/user-attachments/assets/f3b409e2-2686-487f-8596-a3b7e56dca10

**Comment by Nikunjsharma0** [comment]
https://github.com/UstadMobile/UstadMobile/blob/dev-simplified-onboarding/test-end-to-end%2Ftest-descriptions%2F007_002c_user_registration_above_age_13_test_description.md


https://github.com/user-attachments/assets/600d2044-fc5e-4d64-9d49-112c8f562466

**Comment by Nikunjsharma0** [comment]
https://github.com/UstadMobile/UstadMobile/blob/dev-simplified-onboarding/test-end-to-end%2Ftest-descriptions%2F007_002c_user_registration_above_age_13_test_description.md



https://github.com/user-attachments/assets/4cf2b7a3-8462-4fc5-8088-3d52ae825e56

**Comment by Nikunjsharma0** [comment]
https://github.com/UstadMobile/UstadMobile/blob/dev-simplified-onboarding/test-end-to-end%2Ftest-descriptions%2F007_002c_user_registration_above_age_13_test_description.md


https://github.com/user-attachments/assets/8937946a-ff31-4937-be89-28872087aa51

**Comment by Nikunjsharma0** [comment]
https://github.com/UstadMobile/UstadMobile/blob/dev-simplified-onboarding/test-end-to-end%2Ftest-descriptions%2F007_002e_user_registration_personalal_account_can_add_child_profiles.md


https://github.com/user-attachments/assets/2efd21ab-dfcc-4de2-bd02-83a67e2a26dd

**Comment by mikedawson** [comment]
This was shared with Save the Children and worked as expected for them.

**Comment by mikedawson** [comment]
As per @Nikunjsharma0  - learning space list is working for Android and Desktop; not yet for the web

**Comment by mikedawson** [comment]
Must be updated so that the buildconfig is the single point of truth for URLs - AndroidManifest.xml must get its settings from there.
Must ensure that passkey is tested/working for manual local testing and steps for this must be documented.

**Comment by poojaustad** [comment]
Updated test descriptions to reflect changes on the branch dev-simplified-onboarding-learningspacemgr

**Comment by mikedawson** [comment]
Invitation issues @Nikunjsharma0 needs to resolve:

a) Sending by username does not work: the UI requires starting with @ sign, but then searched for @username instead of just user, so the user is never found even when typed correctly.
b) When typing a contact in desktop then hitting enter, the chip is added, but the text still remains
c) Email notification subject line is blank.

**Comment by akshattak** [comment]
Design is updated here: in the tab "Simplified onboarding" : https://balsamiq.cloud/sagy57t/podvg7r

**Comment by mikedawson** [comment]
@akshattak - I have reviewed the design and added comments in Balsamiq.

**Comment by mikedawson** [comment]
@poojaustad I have updated testserver-controller in the dev-simplified-onboarding-primary merge branch - I think it is now ready to run automated tests. I tried using the cypress command and it ran test server/Cypress spec and passed as expected.

**Comment by Nikunjsharma0** [comment]
useMockEmail will only be enabled when running in a test using the Testserver controller emails are stored temporarily for automation testing to check what links are sent
eg  192.168.1.51:8087/api/testemail/list?to=nikunjs.1@gmail.com
it will retun

{
"sentTo": "nikunjs.1@gmail.com", 
"subject": "Invitation to z",
"text": "http://192.168.1.51:8087/umapp/#/ClazzInviteRedeem?inviteCode=e319f744-5cb3-41d2-b33e-bb9a6e9b608b"
}
