### ISSUE TITLE
Admin registration self sign-up

### ISSUE THREAD

**Issue by divyahariharan2103** [UstadMobile/UstadMobile#984]
**User story**

As an Admin, I want to self sign up so that I can create a learning space for my own organization without any delay.

**Background info on user story**

- When an user is an Admin and wants to create a learning space for his/her organization , they should be able to do it without any delay or dependency [e.g. school leader wants to create a learning space for their own school]
- When the user tries to do a self sign up , they should be able to click on the button and be presented with a form to provide details like : Admin Username , Admin Password and Email address.

**Tasks** 

- [x] [Wireframe ](https://balsamiq.cloud/sagy57t/podvg7r/r9F23)for the admin registration self sign up
- [x] Create new branch and pull request.
- [ ]  Create Jenkins job to build automatically on commit and nightly end-to-end build of branch
- [ ]  Update end-to-end testing scenarios in accordance with user story
- [ ]  Add Cypress and Maestro tests to branch based on testing scenarios/wireframes
- [ ]  Implement code as per design and acceptance criteria: requires successful Jenkins build and end-to-end build. Post video of completion of acceptance criteria on task card. Self check for at least 5-10 minutes.
- [ ] Technical note: this branch must be based on the learning space / passkey branch aka Nikunj's branch)
- [ ]  check/verify - run any manual sanity checks required

**Acceptance criteria**

A new branch should be created and [end-to-end testing scenarios](https://github.com/UstadMobile/UstadMobile/tree/primary/test-end-to-end) should be added or modified as required for the user story. Then add links below for all testing scenarios that are newly added or significantly modified:

* [scenario link1](link-to-markdown-for-scenario-in-branch.md) 
* [scenario link2](link-to-markdown-for-scenario-in-branch.md)

**Implementation note**

This must be based on  the dev-simplified-onboarding branch **not** primary. The pull request should target dev-dev-simplified-onboarding.

**Comment by akshattak** [comment]
![Image](https://github.com/user-attachments/assets/4f243b34-ac5a-457d-8820-32a4c39d5fe8)

**Comment by mikedawson** [comment]
@akshattak Please change learning space list to match below:

![Image](https://github.com/user-attachments/assets/60d97c69-fce8-46b6-9bee-72d33e857e6a)

**Comment by akshattak** [comment]
Updated Design: ![Image](https://github.com/user-attachments/assets/96b33d2d-4de4-4dee-bc7f-f3b8e79d88a0)

**Comment by mikedawson** [comment]
@akshattak looks pretty close - few changes:

* LearningSpaceList (third screen)
  * Search should be in the action bar (as it is with all other list screens in app)
  * Done button should be removed  - the user would select one of the options in the list - the done button has no purpose here.
* New Learning Space
  * This should have a CAPTCHA to prevent spam registrations
  * After the user clicks new learning space, before they get to the form, they should go to a terms and conditions screen and must accept

**Comment by akshattak** [comment]
Updated Design: ![Image](https://github.com/user-attachments/assets/73b52149-5fd0-46dc-80e5-56051784cb50)

**Comment by mikedawson** [comment]
@akshattak : minor changes
Screen names:
In middle: is Learning Space List (not new learning space)
Final Screen - CreateNewLearningSpace

Learning Space List screen - search is not expanded by default - on prototype just show the search icon (without textfield etc).

**Comment by akshattak** [comment]
Update design: ![Image](https://github.com/user-attachments/assets/3ccd520b-bcbf-4dc8-9de6-ef4fb4145438)

**Comment by mikedawson** [comment]
@akshattak I think we need a space for subdomain for the CreateNewLearningSpace screen e.g. where someone can enter schoolname.ustadmobile.app . They should only be able to edit the subdomain ('schoolname').

**Comment by mikedawson** [comment]
Initial tasks: checkout/run dev-simplified-onboarding and use the create learning space command as per docs. 
Modify parameters on CreateLearningSpaceUseCase to support a self-registered learning space.

**Comment by sivedcodes** [comment]
> Initial tasks: checkout/run dev-simplified-onboarding and use the create learning space command as per docs. Modify parameters on CreateLearningSpaceUseCase to support a self-registered learning space.

self-registration for a learning space works via CLI command : 

./gradlew app-ktor-server:run --args='newlearningspace --url http://192.168.31.90:8087/ --title Synksys --adminpassword 1234 --isSelfRegistered --subdomain synksys --admincontact admin@example.com --organisationlogo http://example.com/logo.png(orBase64String)  --dburl jdbc:mysql://localhost:3306/synksys_db --dbusername root --dbpassword secret'

**Comment by akshattak** [comment]
@mikedawson @Prashant-Android Please update on this task, pending for a long time now.
