### ISSUE TITLE
Customizable reports: option editing

### ISSUE THREAD

**Issue by mikedawson** [UstadMobile/UstadMobile#992]
[<img src="https://devserver3.ustadmobile.com/jenkins/job/dev-reports-option-editing/badge/icon">](https://devserver3.ustadmobile.com/jenkins/job/dev-reports-option-editing/)

[<img src="https://devserver3.ustadmobile.com/jenkins/job/dev-reports-option-editing-End-To-End-Tests/badge/icon?subject=End-To-End-Tests">](https://devserver3.ustadmobile.com/jenkins/job/dev-reports-option-editing-End-To-End-Tests/)

**User story**

As a _teacher/decision maker/parent_ I want _customize reports_ so that _I can track progress_.

User Background info on user story:

Technical notes:
* The report options are stored as a data class that can be serialized to a string (the string itself will be saved on a database entity)
* A domain UseCase (separate task) must then convert the report options into valid SQL that will generate the requested report

**Tasks**

- [x] @mikedawson review model class structure
- [x] @mikedawson [wireframe](https://balsamiq.cloud/sagy57t/podvg7r/rF904) draft completion
- [x] @poojaustad create Jenkins branch for regular build and end-to-end build
- [x] @poojaustad write (human readable) step-by-step test description
- [x] @poojaustad add Cypress and Maestro test for description as above (expected 11/Feb)
- [x] @Anugraha-sutara update model classes to use enums and sealed classes instead of Int constants
- [x] @Anugraha-sutara implement ReportEdit as per wireframe
- [x] @Anugraha-sutara implement ReportFilterEdit as per wireframe
- [x] @Anugraha-sutara implement conditions to ensure user cannot select incompatible y axis types
- [x] @Anugraha-sutara branch to build successfully pass all existing tests on Jenkins and tests for acceptance criteria
- [x] @poojaustad  update end-to-end test such that it should only login and create the report, not actually use the content.

**Acceptance criteria**

* User should be able to create a new report with options as per the data classes ( see [Report2.kt](https://github.com/UstadMobile/UstadMobile/blob/dev-reports-mvvm/core/src/commonMain/kotlin/com/ustadmobile/core/domain/report/model/Report2.kt) )

Behavior notes:
* Subgrouping needs to have an option for no subgrouping (default)

**Comment by mikedawson** [comment]
Design draft: https://balsamiq.cloud/sagy57t/podvg7r/rF904

**Comment by mikedawson** [comment]
Jenkins jobs created

**Comment by poojaustad** [comment]
Wrote step-by-step test description
On Anugraha's branch dev- reports-option-editing

**Comment by Anugraha-sutara** [comment]
[Screen_recording_20250107_184028.webm](https://github.com/user-attachments/assets/0d543fdf-d67d-4999-b40e-7f66236dda44)

**Comment by Anugraha-sutara** [comment]
Desktop

![Screenshot from 2025-01-08 12-29-10](https://github.com/user-attachments/assets/68faafb7-e68b-433b-ac14-8043ee1b5acd)
![Screenshot from 2025-01-08 12-29-16](https://github.com/user-attachments/assets/152f5b7e-69a2-457a-944c-acef94b82ac0)

**Comment by Anugraha-sutara** [comment]
Web

![Screenshot from 2025-01-08 13-06-08](https://github.com/user-attachments/assets/15ecd753-b504-4ea1-aa99-47945c9ed5a2)
![Screenshot from 2025-01-08 13-06-13](https://github.com/user-attachments/assets/29dcf081-43cb-489d-917d-8d2cc19ef6ce)

**Comment by poojaustad** [comment]
Cypress and Maestro e2e tests are done on the branch dev-reports-option-editing.

**Comment by mikedawson** [comment]
Note: needs updated as per wireframe update to handle custom period and custom fixed date range.

https://balsamiq.cloud/sagy57t/podvg7r/rF904

**Comment by mikedawson** [comment]
Option editing needed updated to match new wireframes; expected by 25/Feb end of day

**Comment by Anugraha-sutara** [comment]
https://github.com/user-attachments/assets/47d9d276-8c65-4c7a-b62c-231a1590b86b

**Comment by Anugraha-sutara** [comment]
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/e1b37cf6-9bef-4870-964e-dd4ad19832f4" />

**Comment by Anugraha-sutara** [comment]
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/cbda38a1-57d9-4024-aa63-388ce24d8f5b" />
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/69c3214a-1466-4bec-96ac-a3ff1b385895" />
